### ISSUE TITLE
ROTA and ROTB are flipped on the pinout diagram

### ISSUE THREAD

**Issue by Rybec** [adafruit/Adafruit-Rotary-Trinkey-PCB#1]
As the title says, ROTA and ROTB are flipped on the pinout diagram.  ROTA is the bottom of the three rotary encoder pins.  (I know, because I am using ROTA as a touch input in CircuitPython, and it's definitely only responding when I apply touch input to the bottom pin.)

**Comment by ladyada** [comment]
@kattni 👁️ ?

**Comment by kattni** [comment]
@Rybec Thanks for pointing this out. Long story short, you're correct, and I have updated the pinout image. Should be good to go now.

**Comment by Rybec** [comment]
No problem!  Glad to help.
